filebeat.inputs:
- type: log
  paths:
    - /var/lib/pgsql/11/data/log/*.csv
  exclude_lines: [".+?08006[^*].+", ".+?08P01[^*].+"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  pipeline: "final_psql_csv"
  index: "psqlslowlog-coupons-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "123456"
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.ilm.enabled: false


filebeat.inputs:
- type: log
  paths:
    - /bdata/data/nowdb2/log-slow-queries.log
  multiline.pattern: '^(# User@Host: |# Time: )'
  multiline.negate: true
  multiline.match: after
  exclude_lines: ['^[\/\w\.]+, Version: .* started with:.*', '^# Time:.*']
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  pipeline: "filebeat-7.0.0-mysql-slowlog-pipeline"
  index: "mysqlslowlog-coupons-%{+yyyy.MM.dd}"
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.ilm.enabled: false
