filebeat.inputs:
- type: log
  paths:
    - /var/lib/pgsql/11/data/log/postgresql-Mon.csv
  exclude_lines: [".+?08006[^*].+", ".+?08P01[^*].+"]
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  pipeline: "psql_pipeline"
  index: "psqlslowlog-xxx-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "123456"
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"
setup.ilm.enabled: false
